#!/bin/sh

# --------------------------------------------------------------------------- #
#                                                                             #
#    Update iSida Jabber Bot from version 3.0 to 3.1                          #
#    Copyright (C) 2012 diSabler <dsy@dsy.name>                               #
#                                                                             #
#    This program is free software: you can redistribute it and/or modify     #
#    it under the terms of the GNU General Public License as published by     #
#    the Free Software Foundation, either version 3 of the License, or        #
#    (at your option) any later version.                                      #
#                                                                             #
#    This program is distributed in the hope that it will be useful,          #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#    GNU General Public License for more details.                             #
#                                                                             #
#    You should have received a copy of the GNU General Public License        #
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.    #
#                                                                             #
# --------------------------------------------------------------------------- #

#su postgres
#createuser -P isidabot
#createdb isidabot -E UTF8 -T template0
#psql -U isidabot isidabot -f pgsql3.1.schema


#python update_to3.py

echo Not available now! Wait!
